apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  annotations:
    clusterlogging.openshift.io/logforwardingtechpreview: "enabled"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 1
      storage: {}
      redundancyPolicy: "ZeroRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
  curation:
    type: "curator"
    curator:
      schedule: "30 3,9,15,21 * * *"
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
---
apiVersion: "logging.openshift.io/v1alpha1"
kind: "LogForwarding"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  outputs:
  - name: syslog
    type: syslog_buffered
    endpoint: "10.46.9.101:515"
    insecure: true
  pipelines:
  - name: logsapp
    inputSource: logs.infra
    outputRefs:
    - syslog
